azs:
- cloud_properties:
    zone: australia-southeast1-a
  name: z1
- cloud_properties:
    zone: australia-southeast1-b
  name: z2
- cloud_properties:
    zone: australia-southeast1-c
  name: z3

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 5

disk_types:
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 3000
  name: default

- name: large
  disk_size: 50_000

networks:
- name: default
  subnets:
  - azs: [z1, z2, z3]
    cloud_properties:
      ephemeral_external_ip: true
      network_name: default
      subnetwork_name: default
      tags:
      - internal
    dns:
    - 8.8.8.8
    gateway: 10.152.0.1
    range: 10.152.0.0/20
    reserved:
    - 10.152.0.1
    - 10.152.0.2
    
  type: manual
- name: vip
  type: vip

vm_extensions:
- cloud_properties:
    target_pool: concourse-lb
  name: lb

vm_types:
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: default

- cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: large

- cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: small

- cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: medium

- cloud_properties:
    machine_type: n1-standard-16
    root_disk_size_gb: 150
    root_disk_type: pd-ssd
  name: extra-large

